### ISSUE TITLE
[Vue warn]: Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by libreY** [hukaibaihu/vue-org-tree#11]
[Vue warn]: Failed to mount component: template or render function not defined.
load plugin - `Vue.component('org-tree-node',Vue2OrgTree)`

**Comment by huhongliang** [comment]
我在子页面import组件的时候无法创建，只有放到main文件中才可以，创建后发现样式丢失，需要手动导入样式文件

**Comment by hukaibaihu** [comment]
请升级到 [1.1.1](https://www.npmjs.com/package/vue2-org-tree)
