### ISSUE TITLE
如何做成左右节点？

### ISSUE THREAD

**Issue by Fdango** [hukaibaihu/vue-org-tree#12]
也就是说org-tree-node-children是右节点，org-tree-node-label里面我也想插入节点

**Comment by wuyuedefeng** [comment]
试试这个[https://github.com/wuyuedefeng/vue-org-tree](https://github.com/wuyuedefeng/vue-org-tree),节点内部通过slot实现，外部可以自定义每个label的样式，可以在外边自定义布局。

**Comment by hukaibaihu** [comment]
> 也就是说org-tree-node-children是右节点，org-tree-node-label里面我也想插入节点

左右节点是 **水平** 排列的，即节点自上向下渲染， 设置 `horizontal` 属性位 `false`
