### ISSUE TITLE
Failed to mount component

### ISSUE THREAD

**Issue by huhongliang** [hukaibaihu/vue-org-tree#16]
cnpm安装后一直提示组件创建失败，参数已经全部带上，想请问是我安装姿势不对还是参数传的有问题
![tim 20181215165412](https://user-images.githubusercontent.com/28997491/50041069-a0cfc000-0089-11e9-8ea6-6eb188f9265e.png)

**Comment by hukaibaihu** [comment]
你指定的props属性不对
```js
props: {
  label: 'label',
  expand: 'expand',
  children: 'children'
}
```
默认的props就是这样子的，一般无需指定。如果你的key跟默认的props中的key不一致，则需要指定props。
比如：
```js
treeData: {
  text: 'label1',
  close: false,
  sub: [{
    text: 'label2',
    close: true,
    sub: [{
      text: 'label3'
    }]
  }]
},
props: {
  label: 'text', // 指定label对应的key
  expand: 'close', // 指定展开|折叠对应的key
  children: 'sub' // 指定children对应的key
}
```

**Comment by ZinLiao** [comment]
> 你指定的props属性不对
> 
> ```js
> props: {
>   label: 'label',
>   expand: 'expand',
>   children: 'children'
> }
> ```
> 
> 默认的props就是这样子的，一般无需指定。如果你的key跟默认的props中的key不一致，则需要指定props。
> 比如：
> 
> ```js
> treeData: {
>   text: 'label1',
>   close: false,
>   sub: [{
>     text: 'label2',
>     close: true,
>     sub: [{
>       text: 'label3'
>     }]
>   }]
> },
> props: {
>   label: 'text', // 指定label对应的key
>   expand: 'close', // 指定展开|折叠对应的key
>   children: 'sub' // 指定children对应的key
> }
> ```



> 你指定的props属性不对
> 
> ```js
> props: {
>   label: 'label',
>   expand: 'expand',
>   children: 'children'
> }
> ```
> 
> 默认的props就是这样子的，一般无需指定。如果你的key跟默认的props中的key不一致，则需要指定props。
> 比如：
> 
> ```js
> treeData: {
>   text: 'label1',
>   close: false,
>   sub: [{
>     text: 'label2',
>     close: true,
>     sub: [{
>       text: 'label3'
>     }]
>   }]
> },
> props: {
>   label: 'text', // 指定label对应的key
>   expand: 'close', // 指定展开|折叠对应的key
>   children: 'sub' // 指定children对应的key
> }
> ```

映射有问题
demo如下：
```
tressData: {
  ID: 123,
  Label: a,
  Children: []
},

props: {
  label: "Label",
  expand: "expand",
  children: "Children"
}
```

组件不报错，但就是无法渲染，节点无文案，点击节点却能返回节点数据
