### ISSUE TITLE
npm 导入此组件后再mian.js中导入后报如下错误

### ISSUE THREAD

**Issue by sunhui44311** [hukaibaihu/vue-org-tree#20]
This relative module was not found:
* ./org-tree.vue?vue&type=style&index=0&lang=less& in ./node_modules/_vue2-org-tree@1.1.1@vue2-org-tree/src/components/org-tree/org-tree.vue

**Comment by wuyuedefeng** [comment]
这个错误一看就是因为你的项目不支持less的css语法导致的啊

**Comment by YiStick** [comment]
`npm i less less-loader`
