### ISSUE TITLE
组件不兼容ie呢

### ISSUE THREAD

**Issue by wqzNGU** [hukaibaihu/vue-org-tree#24]
引入组件之后，项目在ie11上不能正常显示了

**Comment by demigodliu** [comment]
请问解决了吗？

**Comment by leetia316** [comment]
+1

**Comment by 756004854** [comment]
+1

**Comment by gdutwyg** [comment]
这是因为package.json使用了module字段
![image](https://user-images.githubusercontent.com/11848087/67854907-48dc6380-fb4c-11e9-8970-3b370a9029b1.png)

导致会去读src/main.js，main.js引用的es6没有经过babel的转化，ie上面就报错了

**Comment by qianxiaobai** [comment]
请问解决了吗？

**Comment by hukaibaihu** [comment]
可以采用CDN的方式引入，组件会自动安装：
``` html
<script src="https://unpkg.com/vue2-org-tree@1.3.1/dist/index.js"></script>
```
