### ISSUE TITLE
无法访问获取：https://unpkg.com/vue2-org-tree@1.2.0/dist/index.js和https://unpkg.com/vue2-org-tree@1.2.0/dist/style.css

### ISSUE THREAD

**Issue by nongshuqiner** [hukaibaihu/vue-org-tree#28]
通过组件的v1.2.0版本
```html
<script src="https://unpkg.com/vue2-org-tree@1.1.0/dist/index.js"></script>
```
无法引用组件库，但是v1.1.0和v1.1.1可以。

访问结果如图：

![vue2-org-tree@1.2.0/dist/index.js](https://upload-images.jianshu.io/upload_images/4645892-4e48df32c61fa857.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by hukaibaihu** [comment]
请升级至1.2.1版本
