### ISSUE TITLE
on-expand方法失效

### ISSUE THREAD

**Issue by perfect9441** [hukaibaihu/vue-org-tree#29]
on-expand方法在
 <Vue2OrgTree
        :data="list"
        :horizontal="horizontal"
        :collapsable="collapsable"
        @on-expand="onExpand"
        @on-node-click="handleClick"
      />
中失效，只对on-node-click方法有响应

使用浏览器 chrome浏览器   版本 76.0.3809.100（正式版本） （64 位）

vue版本 2.9.6

**Comment by hukaibaihu** [comment]
请提供你的onExpand方法的实现代码，以便于分析问题

**Comment by perfect9441** [comment]
onExpand(data) {
      if ('expand' in data) {
        data.expand = !data.expand
        if (!data.expand && data.children) {
          this.collapse(data.children)
        }
      } else {
        this.$set(data, 'expand', true)
      }
    },

data={
childList: Array(1)
children: Array(1)
expand: "expand"
id: "1"
label: "基础分类"
parent: Object
}

**Comment by hukaibaihu** [comment]
`data` 中的 `expand` 应为 `true|false`

``` js
// eg.
{
  id: 1,
  label: '研发部',
  expand: true,
  children: [{
    id: 2,
    label: '开发',
    expand: true,
    children: [{
      id: 6,
      label: '前端'
    }, {
      id: 7,
      label: '后端'
    }]
  }, {
    id: 3,
    label: '测试'
  }, {
    id: 4,
    label: 'UI'
  }, {
    id: 5,
    label: '产品'
  }]
}
```

**Comment by perfect9441** [comment]
锁定版本至 1.1.1解决问题  感谢及时回复！
