### ISSUE TITLE
刚运行报错怎么办

### ISSUE THREAD

**Issue by iscelinetam** [hukaibaihu/vue-org-tree#32]
ERROR in ./src/components/org-tree/org-tree.vue
Module not found: Error: Can't resolve 'vue' in '/Users/y1/Desktop/vue-org-tree-master 2/src/components/org-tree'
 @ ./src/components/org-tree/org-tree.vue 33:17-31
 @ ./src/components/org-tree/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:9000 webpack/hot/dev-server ./src/main.js

**Comment by gdutwyg** [comment]
博主把vue去掉了，app.vue也去掉了，所以报错了
