### ISSUE TITLE
竖排的时候,样式有bug

### ISSUE THREAD

**Issue by iscelinetam** [hukaibaihu/vue-org-tree#34]
竖排,当只有一列数据的时候,没有排列整齐
<img width="357" alt="屏幕快照 2019-11-01 下午7 01 17" src="https://user-images.githubusercontent.com/47201410/68021015-35abce00-fcdb-11e9-8525-6b2f5be128d4.png">

**Comment by hukaibaihu** [comment]
需要将整棵树几点包裹在可滚动的div内
