### ISSUE TITLE
子节点可以自动展开吗

### ISSUE THREAD

**Issue by alspxl** [hukaibaihu/vue-org-tree#4]
您好! 如标题,请问 子节点可以自动展开吗

**Comment by hukaibaihu** [comment]
可以的

![image](https://user-images.githubusercontent.com/9410341/43113417-e0143e18-8f2c-11e8-9398-fe2051e5066f.png)
``` js
{
    label: 'test',
    expand: true
}
```

定义`expand` 为 `true` 就可以了
