### ISSUE TITLE
如何根据data修改背景颜色

### ISSUE THREAD

**Issue by CrazyMrYan** [hukaibaihu/vue-org-tree#41]

**Comment by CrazyMrYan** [comment]
单独修改某个

**Comment by CrazyMrYan** [comment]
已经修改完成可以查看 [https://github.com/CrazyMrYan/vue-tree-color](look)

**Comment by zongyan86** [comment]
> 已经修改完成可以查看 [https://github.com/CrazyMrYan/vue-tree-color](look)

这个只支持最多两种样式，假设有三种以上的样式，就没辙了。。

**Comment by CrazyMrYan** [comment]
已修复
