### ISSUE TITLE
Vue components for nodes

### ISSUE THREAD

**Issue by overboy20** [hukaibaihu/vue-org-tree#46]
Is it possible to use Vue components for nodes representing instead of `div`? 

And handle events (click, ...) in these components. It will allow easily customize nodes.

Also it could be useful to use components for expand buttons.

**Comment by robinsandstrom** [comment]
`methods: {
    renderContent: function(h, data) {
      return h(Component, {
        props: {
          foo: bar,
          bar: foo
        },
      });
    },
}`

Pass this
