### ISSUE TITLE
正式版本在 render 时会打印 listeners

### ISSUE THREAD

**Issue by mescalchuan** [hukaibaihu/vue-org-tree#47]
感谢大神提供的组件，最近项目有组织架构的需求正好用到。在组件渲染后我发现控制台打印了一系列 listener，查看了源码发现在 node.js 的 render 函数里有一个 console.log。大神有时间可否考虑去掉这个日志？版本 1.3.1。

**Comment by hukaibaihu** [comment]
已修复，请升级版本！
