### ISSUE TITLE
样式丢失

### ISSUE THREAD

**Issue by Hyliuz** [hukaibaihu/vue-org-tree#53]
vue项目启动后发现，组件有效但是样式丢失，build后才能生效，请问这是为什么？

**Comment by hukaibaihu** [comment]
dev 引入 `less` 和 `less-loader` 试试

**Comment by serfend** [comment]
同样复现此问题，所有UI无样式。在config.js中添加了less配置并安装 `less` 和 `less-loader`。问题仍未解决

**Comment by fate2** [comment]
> 同样复现此问题，所有UI无样式。在config.js中添加了less配置并安装 `less` 和 `less-loader`。问题仍未解决
我这样子写解决我的问题
<style scoped>
  @import '~vue2-org-tree/dist/style.css';
</style>
总体是这样子
![image](https://user-images.githubusercontent.com/12712819/103401359-758e6f80-4b83-11eb-98a7-7f60ccc3bd23.png)

**Comment by renmu123** [comment]
#50
