### ISSUE TITLE
文档地址挂了（新加坡节点）

### ISSUE THREAD

**Issue by caohuiboss** [hukaibaihu/vue-org-tree#62]
能否同步一份国内码云的仓库地址和文档呢

**Comment by hukaibaihu** [comment]
https://gitee.com/hukaicode/vue-org-tree

**Comment by caohuiboss** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ste7en"<notifications@github.com&gt;; 
发送时间: 2020年9月14日(星期一) 下午3:20
收件人: "hukaibaihu/vue-org-tree"<vue-org-tree@noreply.github.com&gt;; 
抄送: "曹辉"<2550465923@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hukaibaihu/vue-org-tree] 文档地址挂了（新加坡节点） (#62)





 
https://gitee.com/hukaicode/vue-org-tree
