### ISSUE TITLE
Hey, can i use this with vue-cli3 ?

### ISSUE THREAD

**Issue by mahiraltinkaya** [hukaibaihu/vue-org-tree#66]
Hello bro, 
I think you package is amazing. But i tried with vue3 and doesnt work. I shared a sandbox above. Pls tell me what doesnt work this?  

https://codesandbox.io/live/xo04yl5

**Comment by hukaibaihu** [comment]
Sorry, vue3 is not supported at the moment, support for vue3 is still planned
