### ISSUE TITLE
Can container for label be a template?

### ISSUE THREAD

**Issue by axeh** [hukaibaihu/vue-org-tree#67]
Is there a way, to display some template instead of "just" label?
I would like to add a button or something next to node label.

**Comment by Disperito** [comment]
You can use 'render-content' prop to resolve that. The prop should return a function like:
`renderContent(h, data) {
      return (
        <div>
          <div>{ data.id }</div>
          <div>{ data.label }</div>
        </div>
      )
    }`
The code above used the [JSX](https://cn.vuejs.org/v2/guide/render-function.html).
